trigger:
  - none

parameters:
- name: prm_webAppName
  type: string
  default: 'zdoc-ai-api2'

variables:
  azureServiceConnectionId: 'service-connection-1-web-app-rg'
  webAppName: ${{ parameters.prm_webAppName }}
  vmImageName: 'ubuntu-latest'
  environmentName: 'zdoc-ai-api2'
  pythonVersion: '3.12'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      workingDirectory: $(Build.SourcesDirectory)
      displayName: "Create venv and install dependencies"

    - script: |
        zip -r $(Build.ArtifactStagingDirectory)/app_package.zip app antenv requirements.txt
      workingDirectory: $(Build.SourcesDirectory)
      displayName: 'Package app source + virtual environment'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - job: DeployJob
    pool:
      vmImage: $(vmImageName)

    steps:
    - download: current
      artifact: drop
    - task: AzureWebApp@1
      displayName: 'Deploy Azure Web App: $(webAppName)'
      inputs:
        azureSubscription: $(azureServiceConnectionId)
        appType: 'webAppLinux'
        appName: $(webAppName)
        package: '$(Pipeline.Workspace)/drop/app_package.zip'
        deploymentMethod: zipDeploy
        startUpCommand: 'gunicorn --bind=0.0.0.0:8000 --timeout=600 --worker-class uvicorn.workers.UvicornWorker app.main:app'