trigger:
  branches:
    include:
    - none
variables:
- name: azureServiceConnectionId
  value: 'zweb-app1'
- name: webAppName
  value: 'zflask1'
- name: vmImageName
  value: 'ubuntu-latest'
- name: environmentName
  value: 'zfastapi1'
- name: projectRoot
  value: $(System.DefaultWorkingDirectory)
- name: pythonVersion
  value: '3.9'
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install setup
          pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
        verbose: # (no value); this input is optional
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

    # - task: CmdLine@2
    #   displayName: "Install requirements"
    #   inputs:
    #     script: |
    #       echo ----- setup: installing dependencies --------
    #       echo $(System.DefaultWorkingDirectory)
    #       python --version
    #       pip --version
    #       pip install virtualenv
    #       virtualenv venv39
    #       source venv39/bin/activate
    #       pip install -r requirements.txt
    #     workingDirectory: $(projectRoot)
    # - task: ArchiveFiles@2
    #   displayName: 'Archive files'
    #   inputs:
    #     rootFolderOrFile: "$(Build.SourcesDirectory)"
    #     includeRootFolder: false
    #     archiveType: zip
    #     archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    #     replaceExistingArchive: true
    # # - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    # #   displayName: 'Upload package'
    # #   artifact: drop
    # - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    #   displayName: 'Upload package'
    #   artifact: drop      


- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn:
  - Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python version'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : {{ webAppName }}'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appType: 'webAppLinux'
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              deploymentMethod: zipDeploy

              # The following parameter is specific to the Flask example code. You may
              # or may not need a startup command for your app.
              startUpCommand: 'gunicorn --bind 0.0.0.0:8000 --timeout 600 app.main:app'
              # startUpCommand: 'gunicorn --bind=0.0.0.0 --workers=2 app.main:app'